import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {QvacRuntime,RuntimeEvidenceError,assertCompleteMetrics} from '../../packages/runtime/index.js';
import {QUERY_PROMPT_VERSION,queryResponseFormat,queryHistory,validateQueryInput} from '../../packages/runtime/prompts.js';
import {QUERY_CASES} from './query-evaluation.js';
import {scoreSourceSelection} from './source-selection-scoring.js';
import {withGpuLease} from './gpu-lease.js';
import {sha256} from './transcription-cases.js';
import {assertCanonicalQueryInputs} from './query-evidence-bindings.js';
const [mode,id,validationFile]=process.argv.slice(2);if(!['--freeze','--run'].includes(mode)||!id||!/^20[0-9TZa-z-]+$/.test(id))throw new Error('Use --freeze|--run with a unique dated synthetic protocol ID.');
const root=process.cwd(),prefix=path.join(root,'artifacts/evidence','query-source-selection-'+id),protocolFile=prefix+'-protocol.json';
const devCases=QUERY_CASES.map(c=>({id:c.id,question:c.question,sources:c.sources.map(s=>({...s})),expectedSourceIds:c.expectedStatus==='answered'?['N1']:[],split:'development'}));
if(mode==='--freeze'){
  const schemaSources=Array.from({length:6},(_,i)=>({sourceId:'N'+(i+1),text:'Synthetic schema example.'}));
  const protocol={schemaVersion:1,synthetic:true,releaseAccepted:false,createdAt:new Date().toISOString(),version:QUERY_PROMPT_VERSION,scope:'Source-ID selection from supplied approved excerpts. Four previously seen development questions plus a separately authored fresh validation split received after this prompt freeze. Does not evaluate end-to-end retrieval or establish clinical/general handwriting reliability.',systemPrompt:queryHistory('Synthetic example',schemaSources)[0].content,promptModuleSha256:sha256(await readFile(path.join(root,'packages/runtime/prompts.ts'))),responseFormatForSixSources:queryResponseFormat(schemaSources),responseSchemaRule:'For every request items.enum is exactly the supplied sourceIds in source order; maxItems equals source count. Core separately requires unique authorized IDs and maps whole original approved passages.',loadConfiguration:{ctx_size:4096,device:'gpu',gpu_layers:99,'main-gpu':'dedicated',parallel:1,verbosity:0,reasoning_budget:0},generationConfiguration:{temp:0,seed:42,predict:768,reasoning_budget:0,stream:true,kvCache:false},modelManifest:JSON.parse(await readFile(path.join(root,'MODEL-MANIFEST.json'),'utf8')),developmentCases:devCases,validationCases:'Not yet received by runtime owner. Exact supplied validation manifest and every input will be frozen in the inputs record before any v3 model run.',qualityMethods:'Strict raw JSON object with only sourceIds array; unique authorized IDs; exact expected ID set; selected-ID precision and expected-ID recall; absent-fact abstention. No generated clinical prose or quote rewriting.'};
  await writeFile(protocolFile,JSON.stringify(protocol,null,2),{flag:'wx'});console.log(JSON.stringify({protocolFile,sha256:sha256(await readFile(protocolFile)),version:QUERY_PROMPT_VERSION}));
}else{
  const protocol=JSON.parse(await readFile(protocolFile,'utf8')),protocolSha256=sha256(await readFile(protocolFile));
  if(protocol.version!==QUERY_PROMPT_VERSION||protocol.promptModuleSha256!==sha256(await readFile(path.join(root,'packages/runtime/prompts.ts'))))throw new Error('Frozen prompt implementation changed; evaluation refused.');
  if(!validationFile||path.dirname(validationFile).replaceAll('\\','/')!=='artifacts/evidence')throw new Error('A separate reviewed synthetic validation manifest is required.');
  const validationBytes=await readFile(validationFile),validation=JSON.parse(validationBytes.toString('utf8'));if(validation.synthetic!==true||validation.cases?.length!==6)throw new Error('Exactly six independently authored synthetic validation cases are required.');
  const cases=[...devCases,...validation.cases.map(c=>({...c,split:'fresh-validation'}))];
  if(new Set(cases.map(c=>c.id)).size!==10)throw new Error('Unique evaluation case IDs are required.');
  for(const c of cases){if(typeof c.id!=='string'||!/^[-a-zA-Z0-9]+$/.test(c.id))throw new Error('Evaluation IDs must be safe artifact basenames.');validateQueryInput(c.question,c.sources);if(!Array.isArray(c.expectedSourceIds)||new Set(c.expectedSourceIds).size!==c.expectedSourceIds.length||c.expectedSourceIds.some(id=>!c.sources.some(s=>s.sourceId===id)))throw new Error('Independent expected IDs must be a subset of supplied source IDs.');}
  const inputs={schemaVersion:1,synthetic:true,protocolSha256,validationFile,validationFileSha256:sha256(validationBytes),cases:cases.map(c=>({...c,history:queryHistory(c.question,c.sources),responseFormat:queryResponseFormat(c.sources)}))};assertCanonicalQueryInputs(protocol,inputs,validation);await writeFile(prefix+'-inputs.json',JSON.stringify(inputs,null,2),{flag:'wx'});const inputsSha256=sha256(await readFile(prefix+'-inputs.json'));
  const runtime=new QvacRuntime({projectRoot:root,onStage:e=>console.log(JSON.stringify({runId:e.runId,stage:e.stage}))}),outcomes:any[]=[];
  try{for(const fixture of cases){console.log(JSON.stringify({starting:fixture.id,split:fixture.split,profile:QUERY_PROMPT_VERSION}));const {result,lease}=await withGpuLease(signal=>runtime.answerApprovedNotes({question:fixture.question,sources:fixture.sources,signal}));assertCompleteMetrics(result.metrics);if(result.metrics.output.sha256!==sha256(result.text))throw new Error('Raw output digest mismatch.');const score=scoreSourceSelection(result.text,fixture),record={schemaVersion:1,synthetic:true,releaseAccepted:false,protocolSha256,inputsSha256,fixture,lease,result,score};await writeFile(prefix+'-'+fixture.id+'.json',JSON.stringify(record,null,2),{flag:'wx'});outcomes.push(record);console.log(JSON.stringify({completed:fixture.id,split:fixture.split,runId:result.metrics.runId,score,native:result.metrics.native}));}}
  catch(error){const failure=error instanceof RuntimeEvidenceError?error.evidence:{error:String(error)};await writeFile(prefix+'-failure.json',JSON.stringify({synthetic:true,protocolSha256,inputsSha256,completedCases:outcomes.map(c=>c.fixture.id),failure},null,2),{flag:'wx'});process.exitCode=1;console.error(String(error));}finally{await runtime.close();}
  const summary={schemaVersion:1,synthetic:true,releaseAccepted:false,protocolSha256,inputsSha256,completed:outcomes.length===10,qualityPassed:outcomes.length===10&&outcomes.every(c=>c.score.passed),splits:['development','fresh-validation'].map(split=>({split,cases:outcomes.filter(c=>c.fixture.split===split).length,passed:outcomes.filter(c=>c.fixture.split===split&&c.score.passed).length})),cases:outcomes.map(c=>({id:c.fixture.id,split:c.fixture.split,runId:c.result.metrics.runId,score:c.score,metrics:c.result.metrics})),scope:protocol.scope};await writeFile(prefix+'-summary.json',JSON.stringify(summary,null,2),{flag:'wx'});
}
