import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {QvacRuntime,RuntimeEvidenceError,assertCompleteMetrics} from '../../packages/runtime/index.js';
import {QUERY_PROMPT_VERSION,queryResponseFormat,queryHistory} from '../../packages/runtime/prompts.js';
import {verifyModels} from '../../packages/runtime/models.js';
import {scoreSourceSelection} from './source-selection-scoring.js';
import {withGpuLease} from './gpu-lease.js';
import {sha256} from './transcription-cases.js';
import {assertCanonicalQueryInputs,assertCanonicalModelComparison,assertProtocolModel} from './query-evidence-bindings.js';
const [id,isolatedRoot,sourcePrefix]=process.argv.slice(2),root=process.cwd();
if(!id||!/^20[0-9TZa-z-]+$/.test(id)||path.resolve(isolatedRoot??'')!==path.join(root,'.local/query-4b-eval')||path.dirname(sourcePrefix??'').replaceAll('\\','/')!=='artifacts/evidence')throw new Error('Use the authorized isolated 4B model workspace and prior reviewed synthetic source-selection prefix.');
const originalProtocol=JSON.parse(await readFile(sourcePrefix+'-protocol.json','utf8')),inputs=JSON.parse(await readFile(sourcePrefix+'-inputs.json','utf8'));
if(inputs.protocolSha256!==sha256(await readFile(sourcePrefix+'-protocol.json'))||originalProtocol.version!==QUERY_PROMPT_VERSION||originalProtocol.promptModuleSha256!==sha256(await readFile(path.join(root,'packages/runtime/prompts.ts'))))throw new Error('Frozen query v3 prompt/input binding changed.');
if(path.dirname(inputs.validationFile).replaceAll('\\','/')!=='artifacts/evidence')throw new Error('Validation manifest is outside reviewed synthetic evidence.');
const validationBytes=await readFile(inputs.validationFile);if(inputs.validationFileSha256!==sha256(validationBytes))throw new Error('Canonical validation manifest digest mismatch.');assertCanonicalQueryInputs(originalProtocol,inputs,JSON.parse(validationBytes.toString('utf8')));
const modelDirectory=path.join(root,'.local/models'),verified=await verifyModels(isolatedRoot,modelDirectory,'query');
if(verified.sdkVersion!=='0.18.2'||verified.assets.length!==1||verified.assets[0].constant!=='QWEN3_4B_INST_Q4_K_M'||verified.assets[0].sha256!=='7485fe6f11af29433bc51cab58009521f205840f5b4ae3a32fa7f92e8534fdf5'||verified.assets[0].actualBytes!==2497280256)throw new Error('The approved Qwen3 4B challenger asset is not verified.');
if(inputs.cases.length!==10)throw new Error('Exactly the same ten model-selection cases are required.');
const prefix=path.join(root,'artifacts/evidence','query-model-comparison-'+id),protocol={schemaVersion:1,synthetic:true,heldOut:false,releaseAccepted:false,createdAt:new Date().toISOString(),scope:'One bounded model-size comparison: same frozen v3 prompt, dynamic native schema, ten already-evaluated questions and exact ID references. These cases are now model-selection validation; no untouched-test or clinical reliability claim.',version:QUERY_PROMPT_VERSION,sourceProtocolFile:sourcePrefix+'-protocol.json',sourceProtocolSha256:sha256(await readFile(sourcePrefix+'-protocol.json')),sourceInputsFile:sourcePrefix+'-inputs.json',sourceInputsSha256:sha256(await readFile(sourcePrefix+'-inputs.json')),verifiedAssets:verified.assets,modelManifest:JSON.parse(await readFile(path.join(isolatedRoot,'MODEL-MANIFEST.json'),'utf8')),loadConfiguration:originalProtocol.loadConfiguration,generationConfiguration:originalProtocol.generationConfiguration,cases:inputs.cases.map(c=>({...c,split:'model-selection-'+c.split,history:queryHistory(c.question,c.sources),responseFormat:queryResponseFormat(c.sources)}))};
assertCanonicalModelComparison(protocol,inputs);
await writeFile(prefix+'-protocol.json',JSON.stringify(protocol,null,2),{flag:'wx'});const protocolSha256=sha256(await readFile(prefix+'-protocol.json'));
const runtime=new QvacRuntime({projectRoot:isolatedRoot,modelDirectory,onStage:e=>console.log(JSON.stringify({runId:e.runId,stage:e.stage}))}),outcomes:any[]=[];
try{for(const fixture of protocol.cases){if(!/^[-a-zA-Z0-9]+$/.test(fixture.id))throw new Error('Unsafe evaluation case ID.');console.log(JSON.stringify({starting:fixture.id,model:'QWEN3_4B_INST_Q4_K_M'}));const {result,lease}=await withGpuLease(signal=>runtime.answerApprovedNotes({question:fixture.question,sources:fixture.sources,signal}));assertCompleteMetrics(result.metrics);assertProtocolModel(result.metrics,protocol.modelManifest,'query');if(result.metrics.output.sha256!==sha256(result.text))throw new Error('Raw output digest mismatch.');const score=scoreSourceSelection(result.text,fixture),record={schemaVersion:1,synthetic:true,heldOut:false,releaseAccepted:false,protocolSha256,fixture,lease,result,score};await writeFile(prefix+'-'+fixture.id+'.json',JSON.stringify(record,null,2),{flag:'wx'});outcomes.push(record);console.log(JSON.stringify({completed:fixture.id,runId:result.metrics.runId,score,native:result.metrics.native}));}}
catch(error){const failure=error instanceof RuntimeEvidenceError?error.evidence:{error:String(error)};await writeFile(prefix+'-failure.json',JSON.stringify({synthetic:true,protocolSha256,completedCases:outcomes.map(c=>c.fixture.id),failure},null,2),{flag:'wx'});process.exitCode=1;console.error(String(error));}finally{await runtime.close();}
await writeFile(prefix+'-summary.json',JSON.stringify({schemaVersion:1,synthetic:true,heldOut:false,releaseAccepted:false,protocolSha256,completed:outcomes.length===10,qualityPassed:outcomes.length===10&&outcomes.every(c=>c.score.passed),model:'QWEN3_4B_INST_Q4_K_M',cases:outcomes.map(c=>({id:c.fixture.id,split:c.fixture.split,runId:c.result.metrics.runId,score:c.score,metrics:c.result.metrics})),scope:protocol.scope},null,2),{flag:'wx'});
