/** Initial selection/parser draft generated by the requested Kimi HS CLI; locally reviewed and corrected. */
export interface RecordView { id: string; patientId: string; sourceRevision: number; text: string }
export interface SnapshotView { snapshotId: string; patient: { id: string }; records: RecordView[] }
export interface Source {
  id: string; recordId: string; sourceRevision: number; field: 'text'; start: number; end: number; text: string;
}
interface Candidate extends Omit<Source, 'id' | 'field'> { index: number; score: number }
const STOP_WORDS = new Set('the a an is are was were be been being have has had do does did will would could should may might must can to of in for on with at by from as and or if because where when that which who what this these those i me my we our you your he his she her it its they them their all any each some only than too very just now then tell about show'.split(' '));
const terms = (input: string) => input.toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [];

export function buildSources(snapshot: SnapshotView, question: string): { question: string; sources: Source[]; totalSentences: number; partial: boolean } {
  if (typeof question !== 'string' || !question.trim() || question.length > 1000) throw new Error('Invalid question.');
  if (!snapshot || typeof snapshot.snapshotId !== 'string' || !snapshot.patient || typeof snapshot.patient.id !== 'string'
    || !Array.isArray(snapshot.records) || snapshot.records.length > 50) throw new Error('Invalid snapshot.');
  const seen = new Set<string>();
  for (const record of snapshot.records) {
    if (!record || typeof record.id !== 'string' || !record.id || seen.has(record.id)
      || record.patientId !== snapshot.patient.id || !Number.isSafeInteger(record.sourceRevision) || record.sourceRevision < 1
      || typeof record.text !== 'string' || !record.text || record.text.length > 30000) throw new Error('Invalid record scope.');
    seen.add(record.id);
  }
  const queryTerms = new Set(terms(question).filter(term => !STOP_WORDS.has(term)));
  const candidates: Candidate[] = [];
  let totalSentences = 0;
  for (const record of snapshot.records) {
    let start = 0;
    const append = (end: number) => {
      let first = start, last = end;
      while (first < last && /\s/u.test(record.text[first]!)) first++;
      while (last > first && /\s/u.test(record.text[last - 1]!)) last--;
      start = end;
      if (first === last) return;
      const index = totalSentences++;
      if (last - first > 800) return;
      const text = record.text.slice(first, last);
      const tokens = new Set(terms(text));
      const score = [...queryTerms].reduce((sum, term) => sum + Number(tokens.has(term)), 0);
      if (score) candidates.push({ recordId: record.id, sourceRevision: record.sourceRevision, start: first, end: last, text, score, index });
    };
    for (let index = 0; index < record.text.length; index++) {
      const ch = record.text[index];
      if (ch === '\r') { if (record.text[index + 1] === '\n') index++; append(index + 1); }
      else if (ch === '\n' || ch === ';' || ((ch === '.' || ch === '!' || ch === '?') && (index + 1 === record.text.length || /\s/u.test(record.text[index + 1]!)))) append(index + 1);
    }
    append(record.text.length);
  }
  candidates.sort((a, b) => b.score - a.score || a.index - b.index);
  const sources: Source[] = [];
  let selectedCharacters = 0;
  for (const span of candidates) {
    if (sources.length >= 8) break;
    if (selectedCharacters + span.text.length > 4000) continue;
    sources.push({ id: `S${sources.length + 1}`, recordId: span.recordId, sourceRevision: span.sourceRevision,
      field: 'text', start: span.start, end: span.end, text: span.text });
    selectedCharacters += span.text.length;
  }
  return { question: question.trim(), sources, totalSentences, partial: sources.length < totalSentences };
}

export function parseSelectedIds(raw: string, allowedSources: Source[]): Source[] {
  const invalid = () => { throw new Error('Invalid source selection.'); };
  if (typeof raw !== 'string' || raw.length > 8192) return invalid();
  let parsed: unknown;
  try { parsed = JSON.parse(raw); } catch { return invalid(); }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed) || Object.keys(parsed).join(',') !== 'sourceIds') return invalid();
  const ids = (parsed as { sourceIds: unknown }).sourceIds;
  if (!Array.isArray(ids) || ids.length > 8 || ids.length > allowedSources.length) return invalid();
  const allowed = new Map(allowedSources.map(source => [source.id, source]));
  if (allowed.size !== allowedSources.length) return invalid();
  const seen = new Set<string>();
  return ids.map(id => {
    if (typeof id !== 'string' || !allowed.has(id) || seen.has(id)) return invalid();
    seen.add(id);
    return allowed.get(id)!;
  });
}

export interface MeasuredStats {
  promptTokens: number; emittedTokens: number; timeToFirstToken: number; tokensPerSecond: number;
  generatedTokens?: number; backendDevice?: string;
}
export function requireNativeMeasurements(value: unknown): MeasuredStats {
  const stats = value as Partial<MeasuredStats> | null;
  if (!stats || !Number.isSafeInteger(stats.promptTokens) || stats.promptTokens! <= 0
    || !Number.isSafeInteger(stats.emittedTokens) || stats.emittedTokens! <= 0
    || typeof stats.timeToFirstToken !== 'number' || !Number.isFinite(stats.timeToFirstToken) || stats.timeToFirstToken < 0
    || typeof stats.tokensPerSecond !== 'number' || !Number.isFinite(stats.tokensPerSecond) || stats.tokensPerSecond <= 0
    || (stats.generatedTokens !== undefined && (!Number.isSafeInteger(stats.generatedTokens) || stats.generatedTokens < 0))) {
    throw new Error('Local model run has incomplete native measurements.');
  }
  return stats as MeasuredStats;
}

/** Expo Android release assets can be local file URIs or bare Android resource identifiers. */
export function isBundledAssetUri(uri: unknown): boolean {
  return typeof uri === 'string' && uri.length <= 4096
    && (uri.startsWith('file:///') || /^[a-z0-9_]+$/i.test(uri));
}
