import { spawn } from 'node:child_process';
import { mkdirSync, createWriteStream, existsSync } from 'node:fs';
import { root, localEnv, cli, report } from './lib.mjs';
import { build } from './build.mjs';
const mode = process.argv[2];
const cutIndex = process.argv.indexOf('--cut');
const cut = cutIndex < 0 ? 'cut1' : process.argv[cutIndex + 1];
if (!/^cut[1-9]\d*b?$/.test(cut ?? '')) throw new Error('Expected --cut cut2 (or cut2b).');
const output = `out/psyrec-demo-${cut}.mp4`;
if (mode === 'render' && cut !== 'cut1' && existsSync(output)) throw new Error(`Refusing to overwrite ${output}. Choose a new cut.`);
await build();
if (mode === 'render') await import('./check.mjs');
mkdirSync('out', { recursive: true });
const args = mode === 'dev' ? ['preview', '.', '--foreground'] : mode === 'render' ? ['render', '.', '-o', output, '--fps', '30', '--resolution', 'landscape', '--quality', 'standard', '--workers', '4', '--no-browser-gpu', '--no-best-effort', '--strict'] : [mode, ...process.argv.slice(3)];
report(`Command: \`node ${cli.replace(root, '')} ${args.join(' ')}\` (local cache/profile/temp environment; telemetry disabled).`);
const logPath = `out/${mode}${mode === 'render' && cut !== 'cut1' ? `-${cut}` : ''}.log`;
const log = createWriteStream(logPath);
const child = spawn(process.execPath, [cli, ...args], { cwd: root, env: localEnv(), windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
for (const stream of [child.stdout, child.stderr]) stream.on('data', data => { process.stdout.write(data); log.write(data); });
child.on('error', e => { report(`Command startup failed: ${e.message}`); process.exitCode = 1; });
child.on('exit', code => { log.end(); report(`Command ${mode} exit code: ${code}; log: \`${logPath}\`.`); process.exitCode = code ?? 1; });
